### ISSUE TITLE
More clarity around how to use it?

### ISSUE THREAD

**Issue by jwithington** [postlight/trimmings#10]
I'm super stoked about this project, but a bit confused about how to use it! 

- The installation says "just include trimmings.js in your <head>" But the only spot I see a trimmings.js file is [when I look at the code over on glitch](https://glitch.com/edit/#!/mailbin?path=public/trimmings.js:1:0)
- The Getting Started is more like background; it doesn't quite explain how to use Trimmings. 

I hope this can get a bit more user-friendly, because I loooooove the idea and the background behind it. Y'all rule!

**Comment by johnholdun** [comment]
Hey, thanks for bringing this up!

It's possible to build trimmings.js by cloning the repo and running `yarn install && yarn build`, but that shouldn't be a requirement for use—the resulting file should be included in the repo itself, which can then be downloaded and used directly or referenced from a CDN like [jsdelivr](https://www.jsdelivr.com/). I'll get it in there shortly!

As far as use, the idea is that if you've created an app that follows the guidelines in the Getting Started guide, then you can start using the features right away, but I agree that that's not totally clear. I'm thinking about amending the guide to include a walkthrough for implementing the first Trimmings feature on an existing HTML-serving website. Do you think that would be helpful?

**Comment by jwithington** [comment]
>I'm thinking about amending the guide to include a walkthrough for implementing the first Trimmings feature on an existing HTML-serving website. Do you think that would be helpful?

Absolutely! 

And thanks for the clarifying you did there, already! 😁

**Comment by johnholdun** [comment]
I added a section to the Getting Started guide called ["Your first feature"](https://postlight.github.io/trimmings/getting-started#your-first-feature)! I think there's more to do here still, but I hope this helps.

Closing this issue to keep things tidy, but if you (or anyone else reading this) has more questions about how to use Trimmings, please don't hesitate to open new issues. Thank you!
