### ISSUE TITLE
"Refresh" feature

### ISSUE THREAD

**Issue by snellingio** [postlight/trimmings#12]
See #1 

I would like to see an option to refresh a section every X (where X is in ms, sec, or minutes).

Would essentially be a long polling feature.

**Comment by johnholdun** [comment]
Here's how I imagine using #1's "auto" directive to support this:

Your "refresh" button is a link to the current page, potentially coupled with an `inline` directive to enable refreshing only a small portion of the page. The container targeted by `inline` would be an ancestor of the refresh button, meaning that when the button is clicked, it is removed from the DOM and replaced with a new one.

This new DOM node _also_ has `inline` and `auto` directives, so it starts a new timer to click itself, and the cycle repeats. The refresh button can also be presented to the user, in case they'd like to refresh before the delay kicks in.

Given that this behavior could be satisfied by #1, I'm going to close this as a duplicate. If you have suggestions on why a recurring timer should be implemented in addition to a single delay, let me know and we can reconsider this proposal. Thanks!
