### ISSUE TITLE
"Autosubmit + Replace" feature

### ISSUE THREAD

**Issue by snellingio** [postlight/trimmings#14]
Looking through the autosubmit and the replace javascript. 

Wondering how to best write a "search" feature.

How I'd like it to work: On input change, submit the form, and replace the dom section. I also have a couple of checkboxes that I'd like to do the same thing.

**Comment by johnholdun** [comment]
You can add multiple to directives to a single form. In this case, add `autosubmit` to the form and/or individual inputs, and add `inline` to the form to target a container somewhere on the page.

I'm assuming this answers your question and closing the ticket, but if I misunderstood or this isn't satisfactory for some reason, please leave another comment and let me know. Thanks!
