### ISSUE TITLE
"Trimmings"

### ISSUE THREAD

**Issue by snellingio** [postlight/trimmings#17]
I know that adding `-trimmings` to all the data elements namespaces it nicely. However, it seems a bit silly to write `-trimmings` on every data element. `data-inline` or `data-replace` seem like that wouldn't collide with anything anyways.

Same thing goes with writing css classes with trimmings in them (on the enabled and on the current feature).

Maybe there is a happy medium to be had here.

If not, feel free to close. Just thinking out loud.

**Comment by johnholdun** [comment]
Thanks for your thoughts on this! I struggled with this issue too.

It's true that `trimmings` is a lot to add throughout your HTML—I tried a bunch of shorter names for this project specifically for this reason. In the spirit of the web platform, though, I think it's important to keep these elements namespaced.

Trimmings is meant to potentially exist on a web page _forever_, through many trends and products and third-party scripts and so on. It's likely that something, someday, somewhere, might _also_ try to add a `data-inline` attribute to some element for some reason, which could cause catastrophe if that page also has Trimmings installed. But it's highly unlikely that some third-party script will use these particular attributes, unless that product is _also_ called Trimmings, and then we have a much larger problem to deal with 😬
