### ISSUE TITLE
Docs for "Inline": descriptions for arguments "to" and "from"are reversed

### ISSUE THREAD

**Issue by moozeek** [postlight/trimmings#22]
The arguments "to" and "from" work the other way around (unlike in the documentation)
It should be like that:

- from: A selector targeting the linked page where our content will come from. (required)
- to: A selector targeting an element in the current document where our content will be inserted. (required)

(Thanks for making trimmings, it's great!)

**Comment by johnholdun** [comment]
Huh, how did I miss this? Thank you!
