### ISSUE TITLE
Embed vs Inline

### ISSUE THREAD

**Issue by garygreen** [postlight/trimmings#41]
Is there a significant difference between these two features? I was trying to understand the difference but it's not clear to me from the docs. They seem to serve a similar purpose which is to inline content.

**Comment by johnholdun** [comment]
The main difference is that `embed` works on page load, transparently adding remote content to the page without informing the user, while `inline` awaits user input before taking any action.

Think of `embed` like an include statement in a template, while `inline` is like opening a dropdown or a modal.

Does this help?

**Comment by garygreen** [comment]
Yes that makes sense! Thanks for the explanation.
